export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const AUTH_BEGIN = 'AUTH_BEGIN';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_SAVED_GUIDES_BEGIN = 'GET_SAVED_GUIDES_BEGIN';
export const GET_SAVED_GUIDES = 'GET_SAVED_GUIDES';

export const GET_ALL_GUIDES = 'GET_ALL_GUIDES';
export const GET_GUIDES_BY_HIT_COUNT = 'GET_GUIDES_BY_HIT_COUNT';
export const GET_GUIDES_BY_UPDATED_DATE = 'GET_GUIDES_BY_UPDATED_DATE';
export const GET_GUIDES_BEGIN = 'GET_GUIDES_BEGIN';
